Remove non ascii chars from filename
Non-ascii characters cause weird wine errors when building for win32 on darwin

```
$ nativefier stackedit.io ~/Desktop -o -p win32
```

Stack trace:
```
fixme:heap:RtlSetHeapInformation 0x0 1 0x0 0 stub
Fatal error: Unable to load file
```